---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demoapp-operator
  template:
    metadata:
      labels:
        name: demoapp-operator
    spec:
      serviceAccountName: demoapp-operator
      containers:
        - name: demoapp-operator
          # Replace this with the built image name
          image: "docker.io/mayankb1712/demo-operator:v1"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "demoapp-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: runner
          emptyDir: {}
